export const CREATE_SCHEDULE = "CREATE_SCHEDULE"

export const GET_SUBJECT_NOTICES = "GET_SUBJECT_NOTICES"
export const GET_SUBJECT_NOTICES_ERROR = "GET_SUBJECT_NOTICES_ERROR"
export const GET_SUBJECT_NOTICES_CORRECT = "GET_SUBJECT_NOTICES_CORRECT"
